## 构建数组

### 1. 蛮力构造法

In [1]:
import numpy as np

In [3]:
# 使用np.array() 来创建数组
a = np.array([[1,2,3],[4,5,6]])# 注意有两个中括号
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 也可以指定数据类型
a = np.array([[4,5,6],[7,8,9]], dtype=np.uint8) # 创建2行3列的单字节无符号整型数组
a

array([[4, 5, 6],
       [7, 8, 9]], dtype=uint8)

### 2. 特殊数值法

<p>numpy.zeros(shape, dtype=float, order=‘C’)
<p>numpy.ones(shape, dtype=float, order=‘C’)
<p>numpy.empty(shape, dtype=float, order=‘C’)
<p>numpy.eye(N, M=None, k=0, dtype=float, order='C’)

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3),dtype=np.uint8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [9]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 我们需要一个3行4列、初始值都是5的数组,需要用fill()函数
a = np.empty((3,4), dtype=np.int8)
a.fill(5)
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

### 3. 随机数值法

<p>numpy.random.random(size=None)
<p>numpy.random.randint(low, high=None, size=None, dtype=‘l’)
<p>numpy.random.normal(loc=0.0, scale=1.0, size=None)

In [15]:
# [0, 1)区间内的随机浮点数
b = np.random.random(3)
b

array([0.089127  , 0.19925886, 0.58935649])

In [16]:
b = np.random.random((3, 4))
b

array([[0.13812049, 0.71422001, 0.18564692, 0.45866218],
       [0.01888746, 0.52131715, 0.46067211, 0.03034669],
       [0.07857931, 0.18268256, 0.10621968, 0.66884276]])

In [17]:
# 生成整数
np.random.randint(1,10,size=(4,5))

array([[9, 6, 6, 1, 3],
       [1, 4, 6, 5, 5],
       [9, 8, 3, 7, 3],
       [8, 2, 1, 4, 2]])

### 4. 定长分割法

In [18]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [20]:
np.arange(5.5,11,1.5)

array([ 5.5,  7. ,  8.5, 10. ])

In [21]:
np.arange(3,15).reshape(3,4)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [23]:
# linspace() 函数需要3个参数：一个起点、一个终点，一个返回元素的个数。
np.linspace(0, 4.5, 5) # 0到4.5之间返回5个等距数值（包括0和4.5）

array([0.   , 1.125, 2.25 , 3.375, 4.5  ])

### 构造复杂数组

#### （1）重复构造法

In [24]:
a = np.arange(5)

np.repeat(a,3) # 重复元素3次

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [25]:
np.tile(a,3) # 重复数组3次

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [27]:
a = np.arange(6).reshape((2,3))

np.repeat(a,3,axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [28]:
np.repeat(a,3,axis=1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [29]:
np.tile(a,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [30]:
np.tile(a,(2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

#### (2) 网格构造法

In [31]:
# 表示经纬度的表格
lon = np.linspace(-180,180,37) # 网格精度为10°，共计37个经度点
lat = np.linspace(-90,90,19) # 网格精度为10°，共计19个纬度点

In [33]:
lats, lons = np.mgrid[-90:91:5., -180:181:5.] # 网格精度为5°，网格shape为(37,73)
lons.shape, lats.shape

((37, 73), (37, 73))