## 构建数组

### 1. 蛮力构造法

In [1]:
import numpy as np

In [3]:
# 使用np.array() 来创建数组
a = np.array([[1,2,3],[4,5,6]])# 注意有两个中括号
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 也可以指定数据类型
a = np.array([[4,5,6],[7,8,9]], dtype=np.uint8) # 创建2行3列的单字节无符号整型数组
a

array([[4, 5, 6],
       [7, 8, 9]], dtype=uint8)

### 2. 特殊数值法

<p>numpy.zeros(shape, dtype=float, order=‘C’)
<p>numpy.ones(shape, dtype=float, order=‘C’)
<p>numpy.empty(shape, dtype=float, order=‘C’)
<p>numpy.eye(N, M=None, k=0, dtype=float, order='C’)

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3),dtype=np.uint8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [9]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 我们需要一个3行4列、初始值都是5的数组,需要用fill()函数
